// One-time generator: outlines the RARE PASSAGES wordmark from the Cormorant
// Garamond TTF (variable font, instanced at wght 600 via fontkit).
// Output: src/components/logo-paths.ts
import * as fontkit from "fontkit";
import { writeFileSync, readFileSync } from "node:fs";

const buf = readFileSync("src/app/_og/cormorant-600.ttf");
let font = fontkit.create(buf);
if (font.variationAxes && font.variationAxes.wght) {
  font = font.getVariation({ wght: 600 });
}

const SIZE = 100;
const scale = SIZE / font.unitsPerEm;
const TRACK = SIZE * 0.16;

function textPath(text) {
  const run = font.layout(text);
  let x = 0;
  const parts = [];
  for (let i = 0; i < run.glyphs.length; i++) {
    const glyph = run.glyphs[i];
    const pos = run.positions[i];
    const p = glyph.path.scale(scale, -scale).translate(x + pos.xOffset * scale, 0);
    const d = p.toSVG();
    if (d) parts.push(d);
    x += pos.xAdvance * scale + TRACK;
  }
  return { d: parts.join(" "), width: x - TRACK };
}

const word = textPath("RARE PASSAGES");
writeFileSync("src/components/logo-paths.ts", `// Generated by scripts/generate-logo.mjs — do not edit by hand.
// Wordmark: "RARE PASSAGES", Cormorant Garamond 600, outlined at 100px em, y-down, baseline y=0.
export const WORDMARK_D = ${JSON.stringify(word.d)};
export const WORDMARK_W = ${word.width.toFixed(1)};
`);
console.log("width", word.width.toFixed(1), "NaN:", word.d.includes("NaN"));
